language: node_js

os:
  - osx

before_install:
  - env
  - export LDFLAGS="-L/usr/local/opt/openssl/lib"
  - export CPPFLAGS="-I/usr/local/opt/openssl/include"
  - export PKG_CONFIG_PATH="/usr/local/opt/openssl/lib/pkgconfig"
  - ./scripts/travis-before-install

node_js:
  - 10

script:
  - npm test
  - npm run test-integration

before_deploy:
  - export ARCHIVE_NAME="${TRAVIS_TAG:-latest}-darwin-x64.tar.gz"
  - npm run prebuild
  - file prebuilds/*/*
  - tar -zcvf "$ARCHIVE_NAME" -C prebuilds .

deploy:
  provider: releases
  draft: false
  api_key: "$GH_TOKEN"
  file: "$ARCHIVE_NAME"
  skip_cleanup: true
  on:
    tags: true

notifications:
  email: false